# FHIR 
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_CodeSystem &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_DiagnosticResult &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_Encounter &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_EpisodeOfCare &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_Immunization &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_MedicationAdministration &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_MedicationRequest &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_Observation &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_Order &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_Patient &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_Procedure &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_Schedule &
# Added 05.08.2020
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_AdverseEvent &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_CarePlan &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_Communication &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_ClinicalImpression &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_Condition &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_DeviceRequest &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_DeviceUseStatement &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_Goal &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_ImagingStudy &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_MedicationDispense &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_Questionaire &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_QuestionaireResponse &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_Specimen &
# Added 05.18.2020
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_AllergyIntollerance &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_Appointment &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_AppointmentResponse &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_CareTeam &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_CommunicationResponse &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_DetectedIssue &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_Consent &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_Device &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_DeviceRequest &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_DeviceUseStatement &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_EffectiveEvidenceSynthesis &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_Evidence &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_EvidenceVariable &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_HealthcareService &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_Location &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_Measure &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_MeasureReport &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_MedicationAdministration &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_Organization &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_OrganizationAffiliation &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_Person &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_Practitioner &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_RiskEvidenceSynthesis &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_ResearchElementDefinition &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_ResearchDefinition &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_ResearchStudy &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_ResearchSubject &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_Substance &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_ServiceRequest &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_Substance &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_SupplyDelivery &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_SupplyRequest &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_TestScript &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic FHIRSvr_VerificationResult &
# FHIR - Enterprise by Message Trigger
# Application: Enterprise
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_CodeSystem &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_DiagnosticResult &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_Encounter &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_EpisodeOfCare &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_Immunization &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_MedicationAdministration &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_MedicationRequest &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_Observation &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_Order &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_Patient &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_Procedure &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_Schedule &
# Added 05.08.2020
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_AdverseEvent &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_CarePlan &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_Communication &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_ClinicalImpression &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_Condition &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_DeviceRequest &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_DeviceUseStatement &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_Goal &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_ImagingStudy &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_MedicationDispense &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_Questionaire &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_QuestionaireResponse &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_Specimen &
# Added 05.18.2020
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_AllergyIntollerance &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_Appointment &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_AppointmentResponse &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_CareTeam &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_CommunicationResponse &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_DetectedIssue &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_Consent &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_Device &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_DeviceRequest &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_DeviceUseStatement &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_EffectiveEvidenceSynthesis &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_Evidence &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_EvidenceVariable &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_HealthcareService &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_Location &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_Measure &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_MeasureReport &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_MedicationAdministration &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_Organization &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_OrganizationAffiliation &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_Person &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_Practitioner &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_RiskEvidenceSynthesis &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_ResearchElementDefinition &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_ResearchDefinition &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_ResearchStudy &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_ResearchSubject &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_Substance &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_ServiceRequest &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_Substance &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_SupplyDelivery &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_SupplyRequest &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_TestScript &
bin/kafka-topics.sh --delete --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic Ent_FHIRSvr_VerificationResult &
